version: "3"

services:

  krakend:
    # container_name: krakend
    ports:
      - "80:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    command: run -d -c /etc/krakend/krakend.json
    build: ./
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
        #order: start-first
        failure_action: rollback

  httpbin:
    container_name: httpbin
    image: kong/httpbin
    

#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.0.1.0/24
