version: "3.8"

services:

  krakend:
    ports:
      - "80:8080"
    command: run -d -c /etc/krakend/krakend.json
    build: .
    # deploy:
    #   mode: replicated
    #   replicas: 2
    #   update_config:
    #     parallelism: 1
    #     delay: 20s
    #     failure_action: rollback

  httpbin:
    container_name: httpbin
    image: kong/httpbin
    

#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.0.1.0/24
