version: "3"

services:

  krakend:
    container_name: krakend
    image: devopsfaith/krakend:2.4.3
    ports:
      - "80:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    command: run -d -c /etc/krakend/krakend.json

  httpbin:
    container_name: httpbin
    image: kong/httpbin
    

#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.0.1.0/24
